version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: check-the-test
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data:z
    ports:
      - 6543:5432
